/* DO NOT EDIT THIS FILE - it is machine generated */
#include "JNI/jni.h"
/* Header for class nativelib_AwesomeLib */

/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class nativelib_AwesomeLib */
#ifndef _Included_nativelib_AwesomeLib
#define _Included_nativelib_AwesomeLib
#ifdef __cplusplus
extern "C" {
#endif

    jobject helloworld;
    double size;


#ifdef __cplusplus
}
#endif
#endif